version: '3'

volumes:
  order-db-data:

services:
  order_db:
    image: mysql:5.7
    volumes:
      - order-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=order
    restart: always
    ports:
      - 5557:5557

  order:
    build:
      context: .
    ports:
      - 5557:5557
    volumes:
      - ./app:/app
    links:
      - order_db
    depends_on:
      - order_db
    restart: on-failure
